apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: day2-demo
data:
  index.html: |
    <html>
      <head>
        <title>Day 3 Demo</title>
      </head>
      <body>
        <h1>Welcome to Tilak's Day 3 Practice!</h1>
        <p>This page is served from a ConfigMap mounted into Nginx on OpenShift CRC.</p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: day2-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: docker.io/library/nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: html
          configMap:
            name: nginx-html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy
  namespace: day2-demo
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-deploy
  namespace: day2-demo
spec:
  to:
    kind: Service
    name: nginx-deploy
  port:
    targetPort: 80